src/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from config.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

src/forum/urls.py
from django.urls import path, include

from .views import index, message_create, section, topic, topic_create


urlpatterns = [
    path("", index, name="index"),
    path("section/<int:pk>/", section, name="section"),
    path("section/<int:section>/create_topic/", topic_create, name="topic-create"),
    path("topic/<int:pk>/", topic, name="topic"),
    path("topic/<int:topic>/create_message/", message_create, name="message-create"),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView,
)
from users.views import EditProfileView, ProfileView, SignupView

app_name = 'users'
urlpatterns = [
    path('sign_up/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password_change/', PasswordChangeView.as_view( success_url='/accounts/password_change/done/'), name="password_change"),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset/', PasswordResetView.as_view(success_url='done/'), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view( success_url='/accounts/reset/done/'), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('profile/<int:pk>/', ProfileView.as_view(), name="profile"),
    path('profile/<int:pk>/edit/', EditProfileView.as_view(), name="edit-profile"),
]

src/forum/models.py
from django.contrib import admin
from django.db import models
from django.urls import reverse
from django.conf import settings
from ckeditor.fields import RichTextField


class Section(models.Model):
    name = models.CharField(max_length=120)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("section", kwargs={"pk": self.pk})
    
    @admin.display(boolean=True, ordering='parent')
    def is_top_section(self) -> bool:
        return not self.parent

    def get_last_message(self):
        return Message.objects.filter(topic__in=self.topics.all()).order_by('-created_at').first()


class Topic(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, blank=False, related_name='topics')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False, related_name='topics')
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_closed = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("topic", kwargs={"pk": self.pk})

    def get_last_message(self):
        return self.messages.order_by('-created_at').first()


class Message(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=False, blank=False, related_name='messages')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False, related_name='messages')
    text = RichTextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

src/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

src/forum/forms.py
from django import forms
from django.db import transaction
from ckeditor.widgets import CKEditorWidget

from forum.models import Message, Topic


class TopicForm(forms.Form):
    name = forms.CharField(max_length=255)
    text = forms.CharField(widget=CKEditorWidget())

    @transaction.atomic
    def save(self, section, author) -> Topic:
        topic = Topic.objects.create(section=section, author=author, name=self.cleaned_data['name'])
        message = Message.objects.create(topic=topic, author=author, text=self.cleaned_data['text'])
        return topic


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ('text',)

src/users/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms

from .models import User

class UserCreationForm(auth_forms.UserCreationForm):

    class Meta(auth_forms.UserCreationForm):
        model = User
        fields = ("username", "email",)


class UserChangeForm(auth_forms.UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email', )


class EditProfileForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", )

src/forum/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from forum.forms import MessageForm, TopicForm

from .models import Section, Topic


def index(request):
    sections = Section.objects.filter(parent__isnull=True)
    context = {
        'sections': sections
    }
    return render(request, 'forum/index.html', context=context)


def section(request, pk):
    section = Section.objects.get(pk=pk)

    context = {
        'section': section
    }
    return render(request, 'forum/section.html', context=context)


def topic(request, pk):
    topic = Topic.objects.get(pk=pk)
    form = MessageForm()
    context = {
        'topic': topic,
        'form': form
    }
    return render(request, 'forum/topic.html', context=context)


@login_required
def message_create(request, topic):
    topic = Topic.objects.get(pk=topic)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.topic = topic
            instance.author = request.user
            instance.save()
    
    return redirect(reverse('topic', kwargs={'pk': topic.pk}))


@login_required
def topic_create(request, section):
    section = Section.objects.get(pk=section)

    if section.is_top_section():
        return redirect(reverse('section', kwargs={'pk': section.pk}))

    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            instance = form.save(section, request.user)
            return redirect(reverse('topic', kwargs={'pk': instance.pk}))
    else:
        form = TopicForm()

    context = {
        'section': section,
        'form': form
    }

    return render(request, 'forum/topic_create.html', context=context)

src/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import DetailView, UpdateView

from .models import User
from .forms import EditProfileForm, UserCreationForm


class SignupView(FormView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form: UserCreationForm):
        form.save()
        return super().form_valid(form)


class ProfileView(DetailView):
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'profile'


class EditProfileView(UpdateView):
    model = User
    form_class = EditProfileForm
    template_name = 'users/edit_profile.html'
    context_object_name = 'profile'

    def form_valid(self, form: EditProfileForm):
        form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy('accounts:profile', kwargs={'pk': self.kwargs['pk']})

src/forum/templates/forum/_section_subsections.html
{% if section.children.count %}
<div class="section">
    <div class="section-head">
        <div class="section-info">
            {% if is_top_section %}
            <a href="{{ section.get_absolute_url }}">{{ section.name }}</a>
            {% else %}
            Подразделы
            {% endif %}            
        </div>
        <div class="section-messages">Тем</div>
        <div class="section-last-message">Последнее сообщение</div>
    </div>
    
    <div class="sections">
        {% for child in section.children.all %}
        <div class="section-row">
            <div class="section-info">
                <a href="{{ child.get_absolute_url }}">{{ child.name }}</a>
            </div>
            <div class="section-topics">{{ child.topics.count }}</div>
            <div class="section-last-message">
                <a href="{{ child.get_last_message.topic.get_absolute_url }}">{{ child.get_last_message.topic.name }}</a>
                <div>{{ child.get_last_message.author.username }}</div>
                <div>{{ child.get_last_message.created_at }}</div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endif %}

src/forum/templates/forum/_section_topics.html
{% if section.topics.count %}
<div class="section">
    <div class="section-head">
        <div class="section-info">Темы</div>
        <div class="section-messages">Ответов</div>
        <div class="section-last-message">Последнее сообщение</div>
    </div>
    
    <div class="topics">
        {% for topic in section.topics.all %}
        <div class="topic-row">
            <div class="topic-info">
                <a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>
                <div>{{ topic.author.username }}, {{ topic.created_at }}</div>
            </div>
            <div class="topic-messages">{{ topic.messages.count }}</div>
            <div class="topic-last-message">
                <div>{{ topic.get_last_message.author.username }}</div>
                <div>{{ topic.get_last_message.created_at }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

src/forum/templates/forum/_topic_message.html
<div class="message">
    <div class="message-head">
        <span>{{message.created_at}}</span>
    </div>
    <div class="message-detail">
        <div class="message-author">
            <div>{{ message.author.username }}</div>
            <div>Регистрация {{ message.author.date_joined | date:'d-m-Y' }}</div>
            <div>Сообщений {{ message.author.messages.count }}</div>
        </div>
        <div class="message-body">
            <div>{{ message.text | safe }}</div>
        </div>
    </div>
</div>

src/forum/templates/forum/index.html
{% extends 'base.html' %}

{% block content %}

<ul class="sections">
{% for section in sections %}
<li>
    {% include 'forum/_section_subsections.html' with section=section is_top_section=True %}
</li>
{% endfor %}
</ul>

{% endblock content %}

src/forum/templates/forum/section.html
{% extends 'base.html' %}

{% block content %}

{% if not section.is_top_section %}
<div class="create-topic">
    <a href="{% url 'topic-create' section=section.pk %}">Create topic</a>
</div>
{% endif %}

{% include 'forum/_section_subsections.html' with section=section %}
{% include 'forum/_section_topics.html' with section=section %}

{% endblock content %}

src/forum/templates/forum/topic.html
{% extends 'base.html' %}

{% block content %}

<div class="topic">

<h1>{{ topic.name }}</h1>

{% for message in topic.messages.all %}
    {% include 'forum/_topic_message.html' with message=message %}
{% endfor %}

{% if user.is_authenticated %}
    <h4>Ответить</h4>
    <form action="{% url 'message-create' topic=topic.pk %}" method="post">
        {{ form.media }}
        {{ form.non_field_errors }}
        {% csrf_token %}
        <div class="form-field">
            {{ form.text }}
            <div class="errors">{{ form.text.errors }}</div>
        </div>
        <button type="submit">Send</button>
    </form>
{% else %}
    <div>Авторизуйтесь что бы написать сообщение</div>
{% endif %}

</div>



{% endblock content %}

src/forum/templates/forum/topic_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Create topic</h1>

<form method="post">
    {{ form.media }}
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-field">
        
        <label for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
        {{ form.name }}
        <div class="errors">{{ form.name.errors }}</div>
    </div>
    <div class="form-field">
        {{ form.text }}
        <div class="errors">{{ form.text.errors }}</div>
    </div>
    <button type="submit">Create</button>
</form>
{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load breadcrumbs %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header>
        <div>
            <a href="{% url 'index' %}" class="title">Forum</a>
        </div>
        <div class="links">
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:profile' pk=user.pk %}">{{ user.username }}</a>
                <a href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'accounts:login' %}">Login</a>
                <a href="{% url 'accounts:signup' %}">Sign-up</a>
            {% endif %}
        </div>
    </header>

    <main>
        <div class="container">
            <div id="breadcrumbs">
            {% block breadcrumbs %}{% breadcrumbs %}{% endblock breadcrumbs %}
            </div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>

src/users/templates/users/edit_profile.html
{% extends "base.html" %}

{% block content %}

<div>
    <a href="{% url 'accounts:profile' pk=user.pk %}">Cancel</a>
</div>

<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Save</button>
</form>

{% endblock %}

src/users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}

<div class="profile">

    <div class="profile-left">
        <div class="profile-info">
            <div>
                <h5>{{ profile.username }}</h5>
                <p>Регистрация: {{ profile.date_joined|date:'d-m-Y' }}</p>
                <p>Последняя активность: {{ profile.last_login|date:'H:i d-m-Y' }}</p>
            </div>
            <div>
                <h5>Персональная информация</h5>
                <p>Имя: {{ profile.first_name }}</p>
                <p>Фамилия: {{ profile.last_name }}</p>
                <p>Email: {{ profile.email }}</p>
            </div>
            <div>
                <h5>Управление</h5>
                {% if profile.pk == user.pk %}
                <p><a href="{% url 'accounts:edit-profile' pk=profile.pk %}">Edit profile</a></p>
                <p><a href="{% url 'accounts:password_change' %}">Change password</a></p>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="profile-right">
        <div>Активность</div>
        <div>
            {% for message in profile.messages.all %}
                    <div>
                        <a href="{% url 'topic' pk=message.topic_id %}">{{ message.topic.name }}</a> - {{ message.created_at }}
                    </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock %}